micronaut:
  application:
    name: micronautExampleNamedDatasource
datasources:
  default:
    url: jdbc:h2:mem:devDbDefault;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
  test:
    url: jdbc:h2:mem:devDbTest;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2



flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:migration
    test:
      enabled: true
      locations:
        - classpath:migration
